name: jobsity_chalenge
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  another_flushbar: ^1.10.28
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.3
  expandable_fab_menu: ^0.0.1
  fancy_shimmer_image: ^2.0.2
  flutter_bloc: ^8.0.1
  flutter_rating_bar: ^4.0.0
  hive: ^2.1.0
  local_auth: ^2.0.0
  lottie: ^1.3.0
  path_provider: ^2.0.9
  pinput: ^2.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  bloc_test: ^9.0.3
  flutter_lints: ^1.0.0
  mocktail: ^0.2.0
  mockingjay: ^0.2.0
  import_sorter: ^4.5.1

scripts: derry.yaml

flutter:
  uses-material-design: true

  assets:
    - assets/

import_sorter:
  emojis: false
  comments: false